# Organize the .travis.yml by the steps in the build lifecycle
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

# 0. language and build environment
language: python

python: 3.7
dist: xenial
sudo: true

# 0.5 jobs, stages, and matrix
stages:
  - lint
  - docs
  - test

env:
  - TOXENV=py IGNORED=ignored
  - TOXENV=py OTHER=special

jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=dodgy
    - env: TOXENV=flake8
    - env: TOXENV=manifest
    - env: TOXENV=mypy
    - env: TOXENV=pyroma  # TODO move to deploy?
    - env: TOXENV=radon
    - env: TOXENV=vulture
    - env: TOXENV=xenon

    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs

matrix:
  allow_failures:
    - env: TOXENV=vulture
    - env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs

# 1. apt addons


# 2. cache components
cache: pip


# 3. before_install


# 4. install
install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'

# 5. before_script


# 6. script
script:
  - tox


# 7. before_cache


# 8. after_success/after_failure
after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'


# 9. before_deploy


# 10. deploy


# 11. after_deploy


# 12. after_script


